name: 'adm_exam2'
version: '1.0.0'

profile: "default"

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

data_tests:
  +store_failures: true

models:
  default:
    staging:
      +materialized: incremental
    star:
      +materialized: view
    intermediate:
      +materialized: view
    report:
      +materialized: tables
